<?php
/**
 * @file
 * Donor Rally Campaign feature.
 */
include_once('dr_campaign.features.inc');

/**
 * Implements hook_block_info().
 */
function dr_campaign_block_info() {
  $blocks['campaign_thermometer']['info'] = t('Campaign thermometer');
  $blocks['campaign_thermometer']['cache'] = DRUPAL_NO_CACHE;
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dr_campaign_block_view($delta) {
  module_load_include('inc', 'dr_campaign', 'dr_campaign.block');
  $function = '_dr_campaign_block_' . $delta;
  if (function_exists($function)) {
    return $function();
  }
}

/**
 * Get a campaign's total goal.
 *
 * @param $node
 *   Campaign node object.
 */
function dr_campaign_get_goal($node) {
  return $node->field_campaign_goal[0]['value'];
}

/**
 * Get a campaign's total progress towards the goal.
 *
 * @param $node
 *   Campaign node object.
 */
function dr_campaign_get_total($node) {
  // TODO
  return 77;
}
