<?php
/**
 * @file
 * Donor Rally Campaign feature.
 */
include_once('dr_campaign.features.inc');

/**
 * Implementation of hook_menu().
 */
function dr_campaign_menu() {
  $items['rally'] = array(
    'title' => 'donate',
    'title callback' => 'dr_campaign_title',
    'access arguments' => array('access content'),
    'page callback' => 'dr_campaign_landing_page',
    'page arguments' => array(),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_block().
 */
function dr_campaign_block($op = 'view', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['campaign_thermometer']['info'] = t('Campaign thermometer');
      $blocks['campaign_thermometer']['cache'] = BLOCK_NO_CACHE;

      $blocks['layout_editor']['info'] = t('Layout editor');
      $blocks['layout_editor']['cache'] = BLOCK_NO_CACHE;
      return $blocks;

    case 'view':
      module_load_include('inc', 'dr_campaign', 'dr_campaign.block');
      $function = '_dr_campaign_block_' . $delta;
      if (function_exists($function)) {
        return $function();
      }
  }
}

/**
 * Get a campaign's total goal.
 *
 * @param $node
 *   Campaign node object.
 */
function dr_campaign_get_goal($node) {
  return $node->field_campaign_goal[0]['value'];
}

/**
 * Get a campaign's total progress towards the goal.
 *
 * @param $node
 *   Campaign node object.
 */
function dr_campaign_get_total($node) {
  // TODO
  return 77;
}

/**
 * Page callback for a campaign's landing page.
 */
function dr_campaign_landing_page() {
  $context = context_load('dr_campaign-landing_page');
  if (!$context) {
    $context = ctools_export_new_object('context');
    $context->name = 'dr_campaign-landing_page';
    $context->description = 'Campaign landing page';
    $context->tag = 'donor rally campaign';
    context_save($context);
  }
  context_set('spaces', 'rally', 'dr_campaign-landing_page');
  context_set('context', 'dr_campaign-landing_page', $context);
  return '';
}

function dr_campaign_title() {
  $space = spaces_get_space();
  return $space->group->title;
}